/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.test.kafka.demo.generator.model.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PosInvoce extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4625527071632084839L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PosInvoce\",\"namespace\":\"com.test.kafka.demo.generator.model.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"delivery\",\"type\":{\"type\":\"record\",\"name\":\"DeliveryAddress\",\"fields\":[{\"name\":\"addressline\",\"type\":\"string\"},{\"name\":\"city\",\"type\":\"string\"},{\"name\":\"state\",\"type\":\"string\"},{\"name\":\"pinCode\",\"type\":\"string\"},{\"name\":\"contactNumber\",\"type\":\"string\"}]}},{\"name\":\"items\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"LineItem\",\"fields\":[{\"name\":\"itemCode\",\"type\":\"string\"},{\"name\":\"itemDescription\",\"type\":\"string\"},{\"name\":\"itemQuantity\",\"type\":\"int\"},{\"name\":\"totalValue\",\"type\":\"double\"}]},\"java-class\":\"java.util.List\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PosInvoce> ENCODER =
      new BinaryMessageEncoder<PosInvoce>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PosInvoce> DECODER =
      new BinaryMessageDecoder<PosInvoce>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PosInvoce> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PosInvoce> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PosInvoce> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PosInvoce>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PosInvoce to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PosInvoce from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PosInvoce instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PosInvoce fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence id;
  private java.lang.CharSequence name;
  private com.test.kafka.demo.generator.model.avro.DeliveryAddress delivery;
  private java.util.List<com.test.kafka.demo.generator.model.avro.LineItem> items;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PosInvoce() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param name The new value for name
   * @param delivery The new value for delivery
   * @param items The new value for items
   */
  public PosInvoce(java.lang.CharSequence id, java.lang.CharSequence name, com.test.kafka.demo.generator.model.avro.DeliveryAddress delivery, java.util.List<com.test.kafka.demo.generator.model.avro.LineItem> items) {
    this.id = id;
    this.name = name;
    this.delivery = delivery;
    this.items = items;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return delivery;
    case 3: return items;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    case 2: delivery = (com.test.kafka.demo.generator.model.avro.DeliveryAddress)value$; break;
    case 3: items = (java.util.List<com.test.kafka.demo.generator.model.avro.LineItem>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'delivery' field.
   * @return The value of the 'delivery' field.
   */
  public com.test.kafka.demo.generator.model.avro.DeliveryAddress getDelivery() {
    return delivery;
  }


  /**
   * Sets the value of the 'delivery' field.
   * @param value the value to set.
   */
  public void setDelivery(com.test.kafka.demo.generator.model.avro.DeliveryAddress value) {
    this.delivery = value;
  }

  /**
   * Gets the value of the 'items' field.
   * @return The value of the 'items' field.
   */
  public java.util.List<com.test.kafka.demo.generator.model.avro.LineItem> getItems() {
    return items;
  }


  /**
   * Sets the value of the 'items' field.
   * @param value the value to set.
   */
  public void setItems(java.util.List<com.test.kafka.demo.generator.model.avro.LineItem> value) {
    this.items = value;
  }

  /**
   * Creates a new PosInvoce RecordBuilder.
   * @return A new PosInvoce RecordBuilder
   */
  public static com.test.kafka.demo.generator.model.avro.PosInvoce.Builder newBuilder() {
    return new com.test.kafka.demo.generator.model.avro.PosInvoce.Builder();
  }

  /**
   * Creates a new PosInvoce RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PosInvoce RecordBuilder
   */
  public static com.test.kafka.demo.generator.model.avro.PosInvoce.Builder newBuilder(com.test.kafka.demo.generator.model.avro.PosInvoce.Builder other) {
    if (other == null) {
      return new com.test.kafka.demo.generator.model.avro.PosInvoce.Builder();
    } else {
      return new com.test.kafka.demo.generator.model.avro.PosInvoce.Builder(other);
    }
  }

  /**
   * Creates a new PosInvoce RecordBuilder by copying an existing PosInvoce instance.
   * @param other The existing instance to copy.
   * @return A new PosInvoce RecordBuilder
   */
  public static com.test.kafka.demo.generator.model.avro.PosInvoce.Builder newBuilder(com.test.kafka.demo.generator.model.avro.PosInvoce other) {
    if (other == null) {
      return new com.test.kafka.demo.generator.model.avro.PosInvoce.Builder();
    } else {
      return new com.test.kafka.demo.generator.model.avro.PosInvoce.Builder(other);
    }
  }

  /**
   * RecordBuilder for PosInvoce instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PosInvoce>
    implements org.apache.avro.data.RecordBuilder<PosInvoce> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence name;
    private com.test.kafka.demo.generator.model.avro.DeliveryAddress delivery;
    private com.test.kafka.demo.generator.model.avro.DeliveryAddress.Builder deliveryBuilder;
    private java.util.List<com.test.kafka.demo.generator.model.avro.LineItem> items;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.test.kafka.demo.generator.model.avro.PosInvoce.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.delivery)) {
        this.delivery = data().deepCopy(fields()[2].schema(), other.delivery);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (other.hasDeliveryBuilder()) {
        this.deliveryBuilder = com.test.kafka.demo.generator.model.avro.DeliveryAddress.newBuilder(other.getDeliveryBuilder());
      }
      if (isValidValue(fields()[3], other.items)) {
        this.items = data().deepCopy(fields()[3].schema(), other.items);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing PosInvoce instance
     * @param other The existing instance to copy.
     */
    private Builder(com.test.kafka.demo.generator.model.avro.PosInvoce other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.delivery)) {
        this.delivery = data().deepCopy(fields()[2].schema(), other.delivery);
        fieldSetFlags()[2] = true;
      }
      this.deliveryBuilder = null;
      if (isValidValue(fields()[3], other.items)) {
        this.items = data().deepCopy(fields()[3].schema(), other.items);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.test.kafka.demo.generator.model.avro.PosInvoce.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.test.kafka.demo.generator.model.avro.PosInvoce.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.test.kafka.demo.generator.model.avro.PosInvoce.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.test.kafka.demo.generator.model.avro.PosInvoce.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'delivery' field.
      * @return The value.
      */
    public com.test.kafka.demo.generator.model.avro.DeliveryAddress getDelivery() {
      return delivery;
    }


    /**
      * Sets the value of the 'delivery' field.
      * @param value The value of 'delivery'.
      * @return This builder.
      */
    public com.test.kafka.demo.generator.model.avro.PosInvoce.Builder setDelivery(com.test.kafka.demo.generator.model.avro.DeliveryAddress value) {
      validate(fields()[2], value);
      this.deliveryBuilder = null;
      this.delivery = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'delivery' field has been set.
      * @return True if the 'delivery' field has been set, false otherwise.
      */
    public boolean hasDelivery() {
      return fieldSetFlags()[2];
    }

    /**
     * Gets the Builder instance for the 'delivery' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.test.kafka.demo.generator.model.avro.DeliveryAddress.Builder getDeliveryBuilder() {
      if (deliveryBuilder == null) {
        if (hasDelivery()) {
          setDeliveryBuilder(com.test.kafka.demo.generator.model.avro.DeliveryAddress.newBuilder(delivery));
        } else {
          setDeliveryBuilder(com.test.kafka.demo.generator.model.avro.DeliveryAddress.newBuilder());
        }
      }
      return deliveryBuilder;
    }

    /**
     * Sets the Builder instance for the 'delivery' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.test.kafka.demo.generator.model.avro.PosInvoce.Builder setDeliveryBuilder(com.test.kafka.demo.generator.model.avro.DeliveryAddress.Builder value) {
      clearDelivery();
      deliveryBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'delivery' field has an active Builder instance
     * @return True if the 'delivery' field has an active Builder instance
     */
    public boolean hasDeliveryBuilder() {
      return deliveryBuilder != null;
    }

    /**
      * Clears the value of the 'delivery' field.
      * @return This builder.
      */
    public com.test.kafka.demo.generator.model.avro.PosInvoce.Builder clearDelivery() {
      delivery = null;
      deliveryBuilder = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'items' field.
      * @return The value.
      */
    public java.util.List<com.test.kafka.demo.generator.model.avro.LineItem> getItems() {
      return items;
    }


    /**
      * Sets the value of the 'items' field.
      * @param value The value of 'items'.
      * @return This builder.
      */
    public com.test.kafka.demo.generator.model.avro.PosInvoce.Builder setItems(java.util.List<com.test.kafka.demo.generator.model.avro.LineItem> value) {
      validate(fields()[3], value);
      this.items = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'items' field has been set.
      * @return True if the 'items' field has been set, false otherwise.
      */
    public boolean hasItems() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'items' field.
      * @return This builder.
      */
    public com.test.kafka.demo.generator.model.avro.PosInvoce.Builder clearItems() {
      items = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PosInvoce build() {
      try {
        PosInvoce record = new PosInvoce();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        if (deliveryBuilder != null) {
          try {
            record.delivery = this.deliveryBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("delivery"));
            throw e;
          }
        } else {
          record.delivery = fieldSetFlags()[2] ? this.delivery : (com.test.kafka.demo.generator.model.avro.DeliveryAddress) defaultValue(fields()[2]);
        }
        record.items = fieldSetFlags()[3] ? this.items : (java.util.List<com.test.kafka.demo.generator.model.avro.LineItem>) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PosInvoce>
    WRITER$ = (org.apache.avro.io.DatumWriter<PosInvoce>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PosInvoce>
    READER$ = (org.apache.avro.io.DatumReader<PosInvoce>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeString(this.name);

    this.delivery.customEncode(out);

    long size0 = this.items.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.test.kafka.demo.generator.model.avro.LineItem e0: this.items) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      if (this.delivery == null) {
        this.delivery = new com.test.kafka.demo.generator.model.avro.DeliveryAddress();
      }
      this.delivery.customDecode(in);

      long size0 = in.readArrayStart();
      java.util.List<com.test.kafka.demo.generator.model.avro.LineItem> a0 = this.items;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.test.kafka.demo.generator.model.avro.LineItem>((int)size0, SCHEMA$.getField("items").schema());
        this.items = a0;
      } else a0.clear();
      SpecificData.Array<com.test.kafka.demo.generator.model.avro.LineItem> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.test.kafka.demo.generator.model.avro.LineItem>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.test.kafka.demo.generator.model.avro.LineItem e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.test.kafka.demo.generator.model.avro.LineItem();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 1:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 2:
          if (this.delivery == null) {
            this.delivery = new com.test.kafka.demo.generator.model.avro.DeliveryAddress();
          }
          this.delivery.customDecode(in);
          break;

        case 3:
          long size0 = in.readArrayStart();
          java.util.List<com.test.kafka.demo.generator.model.avro.LineItem> a0 = this.items;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.test.kafka.demo.generator.model.avro.LineItem>((int)size0, SCHEMA$.getField("items").schema());
            this.items = a0;
          } else a0.clear();
          SpecificData.Array<com.test.kafka.demo.generator.model.avro.LineItem> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.test.kafka.demo.generator.model.avro.LineItem>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.test.kafka.demo.generator.model.avro.LineItem e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.test.kafka.demo.generator.model.avro.LineItem();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










